// src/audioConfig.js
const audioConfig = {
    Nivel1: '/AudiosInstrucciones/Nivel1.mp3',
    Nivel2: '/AudiosInstrucciones/Nivel2.mp3',
    Nivel3: '/AudiosInstrucciones/Nivel3.mp3',
    Nivel4: '/AudiosInstrucciones/Nivel4.mp3',
    cartilla:'/AudiosInstrucciones/cartilla.mp3',
    SelecCartilla:'/AudiosInstrucciones/SelecCartilla.mp3',
    PulsarImg:'/AudiosInstrucciones/PulsarImg.mp3',
    Memorias:'/AudiosInstrucciones/Memorias.mp3',
    InstruccionMemorias:'/AudiosInstrucciones/InstruccionMemorias.mp3',
    EjemploMemoria:'/AudiosInstrucciones/EjemploMemoria.mp3',
    ActividadLv1:'/AudiosInstrucciones/ActividadLv1.mp3',
    InstruccionLv1:'/AudiosInstrucciones/InstruccionLv1.mp3',
    Laboratorio:'/AudiosInstrucciones/Laboratorio.mp3',
    InstruccionCV:'/AudiosInstrucciones/InstruccionCV.mp3',
    InstruccionVC:'/AudiosInstrucciones/InstruccionVC.mp3',
    InstruccionCVC:'/AudiosInstrucciones/InstruccionCVC.mp3',
    InstruccionCCV:'/AudiosInstrucciones/InstruccionCCV.mp3',
    Misterio:'/AudiosInstrucciones/Misterio.mp3',
    InstruccionMisterio:'/AudiosInstrucciones/InstruccionMisterio.mp3',
    ActividadLv2:'/AudiosInstrucciones/ActividadLv2.mp3',
    InstruccionLv2:'/AudiosInstrucciones/InstruccionLv2.mp3',
    Recetas:'/AudiosInstrucciones/Recetas.mp3',
    InstruccionRecetas:'/AudiosInstrucciones/InstruccionRecetas.mp3',
    harina:'/AudiosInstrucciones/Receta/Harina.mp3',
    azucar:'/AudiosInstrucciones/Receta/Azucar.mp3',
    leche:'/AudiosInstrucciones/Receta/Leche.mp3',
    huevos:'/AudiosInstrucciones/Receta/Huevos.mp3',
    vainilla:'/AudiosInstrucciones/Receta/Vainilla.mp3',
    mantequilla:'/AudiosInstrucciones/Receta/Mantequilla.mp3',
    Fruta:'/AudiosInstrucciones/Fruta.mp3',
    InstruccionFruta:'/AudiosInstrucciones/InstruccionFruta.mp3',
    Oraciones:'/AudiosInstrucciones/Oraciones.mp3',
    InstruccionOraciones:'/AudiosInstrucciones/InstruccionOraciones.mp3',
    Adivinanzas:'/AudiosInstrucciones/Adivinanzas.mp3',
    InstruccionAdivinanzas:'/AudiosInstrucciones/InstruccionAdivinanzas.mp3',
    ActividadLv4:'/AudiosInstrucciones/ActividadLv4.mp3',
    InstruccionLv4:'/AudiosInstrucciones/InstruccionLv4.mp3',
    AyudaLv4:'/AudiosInstrucciones/AyudaLv4.mp3',
    Historias:'/AudiosInstrucciones/Historias.mp3',
    ClicHistoria:'/AudiosInstrucciones/ClicHistoria.mp3',
    InstruccionHistorias:'/AudiosInstrucciones/InstruccionHistorias.mp3',
    VallePerdido:'/AudiosInstrucciones/VallePerdido.mp3',

    letraA: '/AudiosInstrucciones/AudiosLetras/LetraA.mp3',
    abeja: '/AudiosInstrucciones/AudiosObjetos/abeja.mp3',
    avion: '/AudiosInstrucciones/AudiosObjetos/avion.mp3',
    letraB: '/AudiosInstrucciones/AudiosLetras/LetraB.mp3',
    bicicleta: '/AudiosInstrucciones/AudiosObjetos/bicicleta.mp3',
    botas: '/AudiosInstrucciones/AudiosObjetos/botas.mp3',
    letraC: '/AudiosInstrucciones/AudiosLetras/LetraC.mp3',
    carro: '/AudiosInstrucciones/AudiosObjetos/carro.mp3',
    casa: '/AudiosInstrucciones/AudiosObjetos/casa.mp3',
    letraD: '/AudiosInstrucciones/AudiosLetras/LetraD.mp3',
    delfin: '/AudiosInstrucciones/AudiosObjetos/delfin.mp3',
    dinosaurio: '/AudiosInstrucciones/AudiosObjetos/dinosaurio.mp3',
    letraE: '/AudiosInstrucciones/AudiosLetras/LetraE.mp3',
    elefante: '/AudiosInstrucciones/AudiosObjetos/elefante.mp3',
    erizo: '/AudiosInstrucciones/AudiosObjetos/erizo.mp3',
    letraF: '/AudiosInstrucciones/AudiosLetras/LetraF.mp3',
    flauta: '/AudiosInstrucciones/AudiosObjetos/flauta.mp3',
    flores: '/AudiosInstrucciones/AudiosObjetos/flores.mp3',
    letraG: '/AudiosInstrucciones/AudiosLetras/LetraG.mp3',
    gato: '/AudiosInstrucciones/AudiosObjetos/gato.mp3',
    guayaba: '/AudiosInstrucciones/AudiosObjetos/guayaba.mp3',
    letraH: '/AudiosInstrucciones/AudiosLetras/LetraH.mp3',
    hielo: '/AudiosInstrucciones/AudiosObjetos/hielo.mp3',
    hormiga: '/AudiosInstrucciones/AudiosObjetos/hormiga.mp3',
    letraI: '/AudiosInstrucciones/AudiosLetras/LetraI.mp3',
    iguana: '/AudiosInstrucciones/AudiosObjetos/iguana.mp3',
    iman: '/AudiosInstrucciones/AudiosObjetos/iman.mp3',
    letraJ: '/AudiosInstrucciones/AudiosLetras/LetraJ.mp3',
    jabon: '/AudiosInstrucciones/AudiosObjetos/jabon.mp3',
    jirafa: '/AudiosInstrucciones/AudiosObjetos/jirafa.mp3',
    letraK: '/AudiosInstrucciones/AudiosLetras/LetraK.mp3',
    karate: '/AudiosInstrucciones/AudiosObjetos/karate.mp3',
    koala: '/AudiosInstrucciones/AudiosObjetos/koala.mp3',
    letraL: '/AudiosInstrucciones/AudiosLetras/LetraL.mp3',
    lampara: '/AudiosInstrucciones/AudiosObjetos/lampara.mp3',
    leon: '/AudiosInstrucciones/AudiosObjetos/leon.mp3',
    letraM: '/AudiosInstrucciones/AudiosLetras/LetraM.mp3',
    mariposa: '/AudiosInstrucciones/AudiosObjetos/mariposa.mp3',
    mesa: '/AudiosInstrucciones/AudiosObjetos/mesa.mp3',
    letraN: '/AudiosInstrucciones/AudiosLetras/LetraN.mp3',
    nido: '/AudiosInstrucciones/AudiosObjetos/nido.mp3',
    nube: '/AudiosInstrucciones/AudiosObjetos/nube.mp3',
    letraÑ: '/AudiosInstrucciones/AudiosLetras/LetraÑ.mp3',
    ñandu: '/AudiosInstrucciones/AudiosObjetos/ñandu.mp3',
    letraO: '/AudiosInstrucciones/AudiosLetras/LetraO.mp3',
    olla: '/AudiosInstrucciones/AudiosObjetos/olla.mp3',
    oso: '/AudiosInstrucciones/AudiosObjetos/oso.mp3',
    letraP: '/AudiosInstrucciones/AudiosLetras/LetraP.mp3',
    pelota: '/AudiosInstrucciones/AudiosObjetos/pelota.mp3',
    pinguino: '/AudiosInstrucciones/AudiosObjetos/pinguino.mp3',
    letraQ: '/AudiosInstrucciones/AudiosLetras/LetraQ.mp3',
    queso: '/AudiosInstrucciones/AudiosObjetos/queso.mp3',
    letraR: '/AudiosInstrucciones/AudiosLetras/LetraR.mp3',
    raton: '/AudiosInstrucciones/AudiosObjetos/raton.mp3',
    reloj: '/AudiosInstrucciones/AudiosObjetos/reloj.mp3',
    letraS: '/AudiosInstrucciones/AudiosLetras/LetraS.mp3',
    silla: '/AudiosInstrucciones/AudiosObjetos/silla.mp3',
    sol: '/AudiosInstrucciones/AudiosObjetos/sol.mp3',
    letraT: '/AudiosInstrucciones/AudiosLetras/LetraT.mp3',
    taza: '/AudiosInstrucciones/AudiosObjetos/taza.mp3',
    toro: '/AudiosInstrucciones/AudiosObjetos/toro.mp3',
    letraU: '/AudiosInstrucciones/AudiosLetras/LetraU.mp3',
    uvas: '/AudiosInstrucciones/AudiosObjetos/uvas.mp3',
    letraV: '/AudiosInstrucciones/AudiosLetras/LetraV.mp3',
    vaca: '/AudiosInstrucciones/AudiosObjetos/vaca.mp3',
    vaso: '/AudiosInstrucciones/AudiosObjetos/vaso.mp3',
    letraW: '/AudiosInstrucciones/AudiosLetras/LetraW.mp3',
    waffle: '/AudiosInstrucciones/AudiosObjetos/waffle.mp3',
    wifi: '/AudiosInstrucciones/AudiosObjetos/wifi.mp3',
    letraX: '/AudiosInstrucciones/AudiosLetras/LetraX.mp3',
    xilofono: '/AudiosInstrucciones/AudiosObjetos/xilofono.mp3',
    letraY: '/AudiosInstrucciones/AudiosLetras/LetraY.mp3',
    yate: '/AudiosInstrucciones/AudiosObjetos/yate.mp3',
    yoyo: '/AudiosInstrucciones/AudiosObjetos/yoyo.mp3',
    letraZ: '/AudiosInstrucciones/AudiosLetras/LetraZ.mp3',
    zanahoria: '/AudiosInstrucciones/AudiosObjetos/zanahoria.mp3',
    zapato: '/AudiosInstrucciones/AudiosObjetos/zapato.mp3',
   
  };
  
  export default audioConfig;
  